-- Add new profile fields to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "whatsapp" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nickname" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "yearEnrolled" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "currentSemester" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "academicAdvisor" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "targetIps" DOUBLE PRECISION;
